CONCEPT_CONFIG:
    INSTANCE_DIR_ROOT: "./instance_dir/"
    INSTANCE_NAME: 'yusufjkhan1'
    CLASS_NAME: 'man'
TRAINING_CONFIG:
    CONCEPTS_LIST: 'concepts_list.json'
    MODEL_NAME: "runwayml/stable-diffusion-v1-5"
    OUTPUT_DIR: "./weights/"
    PRETRAINED_VAE_NAME_OR_PATH: "stabilityai/sd-vae-ft-mse"
    